### ISSUE TITLE
what is the main differences/improvent from sukiyaki?

### ISSUE THREAD

**Issue by jiangzidong** [mil-tokyo/sukiyaki2#1]
Hi
Could you tell us the main improvements/differences with the original project "sukiyaki"?
Why choose to create a new project, rather than patch into 'sukiyaki'?

Thanks

**Comment by milhidaka** [comment]
The fundamental idea of sukiyaki and sukiyaki2 is the same; building deep learning framework that is fast enough to train modern CNNs (using WebCL / OpenCL).
The main differences of sukiyaki2 from sukiyaki are:

- use sushi2 instead of sushi for underlying matrix library.
- layers needed for large-scale CNNs are added.
   - dropout, data augmentation etc.
- functionalities of each module are more separated.
   - For example, optimizer is embedded in implementations of each layer (conv, fc) in sukiyaki.
- implemented in TypeScript for gaining more support from IDE.

The reason why I setup new project is that the architecture of sushi is inconvenient for further improvement of sukiyaki.
For example, sushi only supports two-dimensional matrices. In CNNs, support for four-dimensional matrices in matrix library layer much simplifies implementation of convolutional layer.
It was difficult to keep compatibility and make improvements given current code, so I decided to implement sushi2 with new function set and internal data structure.
sushi2 is incompatible with sushi, so I implemented sukiyaki2 using the new function set of sushi2.

**Comment by jiangzidong** [comment]
Thanks very much for your explaination！

**Comment by jiangzidong** [comment]
Could you give me an example about the 4-d matrices in sushi2? Thanks

**Comment by milhidaka** [comment]
Wrote document about matrix manipulation, including 3d case.
https://mil-tokyo.github.io/sushi2/indexing.html
